/*
 * BCA
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bca
// InlineObject struct for InlineObject
type InlineObject struct {
	R1 string `json:"r1"`
	Value28D129 string `json:"value%28D1%29"`
	Value28startDt29 string `json:"value%28startDt%29"`
	Value28startMt29 string `json:"value%28startMt%29"`
	Value28startYr29 string `json:"value%28startYr%29"`
	Value28endDt29 string `json:"value%28endDt%29"`
	Value28endMt29 string `json:"value%28endMt%29"`
	Value28endYr29 string `json:"value%28endYr%29"`
}
