/*
 * BCA
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bca
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	Value28userId29 string `json:"value%28user_id%29"`
	Value28pswd29 string `json:"value%28pswd%29"`
	Value28Submit29 string `json:"value%28Submit%29"`
	Value28actions29 string `json:"value%28actions%29"`
	Value28userIp29 string `json:"value%28user_ip%29"`
	UserIp string `json:"user_ip"`
	Value28mobile29 string `json:"value%28mobile%29"`
	Value28browserInfo29 string `json:"value%28browser_info%29"`
	Mobile string `json:"mobile"`
}
