/*
 * BCA
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bca

import (
	"encoding/json"
)

// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	Value28userId29 string `json:"value%28user_id%29"`
	Value28pswd29 string `json:"value%28pswd%29"`
	Value28Submit29 string `json:"value%28Submit%29"`
	Value28actions29 string `json:"value%28actions%29"`
	Value28userIp29 string `json:"value%28user_ip%29"`
	UserIp string `json:"user_ip"`
	Value28mobile29 string `json:"value%28mobile%29"`
	Value28browserInfo29 string `json:"value%28browser_info%29"`
	Mobile string `json:"mobile"`
}

// NewInlineObject1 instantiates a new InlineObject1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1(value28userId29 string, value28pswd29 string, value28Submit29 string, value28actions29 string, value28userIp29 string, userIp string, value28mobile29 string, value28browserInfo29 string, mobile string, ) *InlineObject1 {
	this := InlineObject1{}
	this.Value28userId29 = value28userId29
	this.Value28pswd29 = value28pswd29
	this.Value28Submit29 = value28Submit29
	this.Value28actions29 = value28actions29
	this.Value28userIp29 = value28userIp29
	this.UserIp = userIp
	this.Value28mobile29 = value28mobile29
	this.Value28browserInfo29 = value28browserInfo29
	this.Mobile = mobile
	return &this
}

// NewInlineObject1WithDefaults instantiates a new InlineObject1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1WithDefaults() *InlineObject1 {
	this := InlineObject1{}
	return &this
}

// GetValue28userId29 returns the Value28userId29 field value
func (o *InlineObject1) GetValue28userId29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28userId29
}

// GetValue28userId29Ok returns a tuple with the Value28userId29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28userId29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28userId29, true
}

// SetValue28userId29 sets field value
func (o *InlineObject1) SetValue28userId29(v string) {
	o.Value28userId29 = v
}

// GetValue28pswd29 returns the Value28pswd29 field value
func (o *InlineObject1) GetValue28pswd29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28pswd29
}

// GetValue28pswd29Ok returns a tuple with the Value28pswd29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28pswd29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28pswd29, true
}

// SetValue28pswd29 sets field value
func (o *InlineObject1) SetValue28pswd29(v string) {
	o.Value28pswd29 = v
}

// GetValue28Submit29 returns the Value28Submit29 field value
func (o *InlineObject1) GetValue28Submit29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28Submit29
}

// GetValue28Submit29Ok returns a tuple with the Value28Submit29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28Submit29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28Submit29, true
}

// SetValue28Submit29 sets field value
func (o *InlineObject1) SetValue28Submit29(v string) {
	o.Value28Submit29 = v
}

// GetValue28actions29 returns the Value28actions29 field value
func (o *InlineObject1) GetValue28actions29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28actions29
}

// GetValue28actions29Ok returns a tuple with the Value28actions29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28actions29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28actions29, true
}

// SetValue28actions29 sets field value
func (o *InlineObject1) SetValue28actions29(v string) {
	o.Value28actions29 = v
}

// GetValue28userIp29 returns the Value28userIp29 field value
func (o *InlineObject1) GetValue28userIp29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28userIp29
}

// GetValue28userIp29Ok returns a tuple with the Value28userIp29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28userIp29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28userIp29, true
}

// SetValue28userIp29 sets field value
func (o *InlineObject1) SetValue28userIp29(v string) {
	o.Value28userIp29 = v
}

// GetUserIp returns the UserIp field value
func (o *InlineObject1) GetUserIp() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.UserIp
}

// GetUserIpOk returns a tuple with the UserIp field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetUserIpOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserIp, true
}

// SetUserIp sets field value
func (o *InlineObject1) SetUserIp(v string) {
	o.UserIp = v
}

// GetValue28mobile29 returns the Value28mobile29 field value
func (o *InlineObject1) GetValue28mobile29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28mobile29
}

// GetValue28mobile29Ok returns a tuple with the Value28mobile29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28mobile29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28mobile29, true
}

// SetValue28mobile29 sets field value
func (o *InlineObject1) SetValue28mobile29(v string) {
	o.Value28mobile29 = v
}

// GetValue28browserInfo29 returns the Value28browserInfo29 field value
func (o *InlineObject1) GetValue28browserInfo29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28browserInfo29
}

// GetValue28browserInfo29Ok returns a tuple with the Value28browserInfo29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetValue28browserInfo29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28browserInfo29, true
}

// SetValue28browserInfo29 sets field value
func (o *InlineObject1) SetValue28browserInfo29(v string) {
	o.Value28browserInfo29 = v
}

// GetMobile returns the Mobile field value
func (o *InlineObject1) GetMobile() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetMobileOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Mobile, true
}

// SetMobile sets field value
func (o *InlineObject1) SetMobile(v string) {
	o.Mobile = v
}

func (o InlineObject1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value%28user_id%29"] = o.Value28userId29
	}
	if true {
		toSerialize["value%28pswd%29"] = o.Value28pswd29
	}
	if true {
		toSerialize["value%28Submit%29"] = o.Value28Submit29
	}
	if true {
		toSerialize["value%28actions%29"] = o.Value28actions29
	}
	if true {
		toSerialize["value%28user_ip%29"] = o.Value28userIp29
	}
	if true {
		toSerialize["user_ip"] = o.UserIp
	}
	if true {
		toSerialize["value%28mobile%29"] = o.Value28mobile29
	}
	if true {
		toSerialize["value%28browser_info%29"] = o.Value28browserInfo29
	}
	if true {
		toSerialize["mobile"] = o.Mobile
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject1 struct {
	value *InlineObject1
	isSet bool
}

func (v NullableInlineObject1) Get() *InlineObject1 {
	return v.value
}

func (v *NullableInlineObject1) Set(val *InlineObject1) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1(val *InlineObject1) *NullableInlineObject1 {
	return &NullableInlineObject1{value: val, isSet: true}
}

func (v NullableInlineObject1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


