/*
 * BCA
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bca

import (
	"encoding/json"
)

// InlineObject struct for InlineObject
type InlineObject struct {
	R1 string `json:"r1"`
	Value28D129 string `json:"value%28D1%29"`
	Value28startDt29 string `json:"value%28startDt%29"`
	Value28startMt29 string `json:"value%28startMt%29"`
	Value28startYr29 string `json:"value%28startYr%29"`
	Value28endDt29 string `json:"value%28endDt%29"`
	Value28endMt29 string `json:"value%28endMt%29"`
	Value28endYr29 string `json:"value%28endYr%29"`
}

// NewInlineObject instantiates a new InlineObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject(r1 string, value28D129 string, value28startDt29 string, value28startMt29 string, value28startYr29 string, value28endDt29 string, value28endMt29 string, value28endYr29 string, ) *InlineObject {
	this := InlineObject{}
	this.R1 = r1
	this.Value28D129 = value28D129
	this.Value28startDt29 = value28startDt29
	this.Value28startMt29 = value28startMt29
	this.Value28startYr29 = value28startYr29
	this.Value28endDt29 = value28endDt29
	this.Value28endMt29 = value28endMt29
	this.Value28endYr29 = value28endYr29
	return &this
}

// NewInlineObjectWithDefaults instantiates a new InlineObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObjectWithDefaults() *InlineObject {
	this := InlineObject{}
	return &this
}

// GetR1 returns the R1 field value
func (o *InlineObject) GetR1() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.R1
}

// GetR1Ok returns a tuple with the R1 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetR1Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.R1, true
}

// SetR1 sets field value
func (o *InlineObject) SetR1(v string) {
	o.R1 = v
}

// GetValue28D129 returns the Value28D129 field value
func (o *InlineObject) GetValue28D129() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28D129
}

// GetValue28D129Ok returns a tuple with the Value28D129 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28D129Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28D129, true
}

// SetValue28D129 sets field value
func (o *InlineObject) SetValue28D129(v string) {
	o.Value28D129 = v
}

// GetValue28startDt29 returns the Value28startDt29 field value
func (o *InlineObject) GetValue28startDt29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28startDt29
}

// GetValue28startDt29Ok returns a tuple with the Value28startDt29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28startDt29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28startDt29, true
}

// SetValue28startDt29 sets field value
func (o *InlineObject) SetValue28startDt29(v string) {
	o.Value28startDt29 = v
}

// GetValue28startMt29 returns the Value28startMt29 field value
func (o *InlineObject) GetValue28startMt29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28startMt29
}

// GetValue28startMt29Ok returns a tuple with the Value28startMt29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28startMt29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28startMt29, true
}

// SetValue28startMt29 sets field value
func (o *InlineObject) SetValue28startMt29(v string) {
	o.Value28startMt29 = v
}

// GetValue28startYr29 returns the Value28startYr29 field value
func (o *InlineObject) GetValue28startYr29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28startYr29
}

// GetValue28startYr29Ok returns a tuple with the Value28startYr29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28startYr29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28startYr29, true
}

// SetValue28startYr29 sets field value
func (o *InlineObject) SetValue28startYr29(v string) {
	o.Value28startYr29 = v
}

// GetValue28endDt29 returns the Value28endDt29 field value
func (o *InlineObject) GetValue28endDt29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28endDt29
}

// GetValue28endDt29Ok returns a tuple with the Value28endDt29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28endDt29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28endDt29, true
}

// SetValue28endDt29 sets field value
func (o *InlineObject) SetValue28endDt29(v string) {
	o.Value28endDt29 = v
}

// GetValue28endMt29 returns the Value28endMt29 field value
func (o *InlineObject) GetValue28endMt29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28endMt29
}

// GetValue28endMt29Ok returns a tuple with the Value28endMt29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28endMt29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28endMt29, true
}

// SetValue28endMt29 sets field value
func (o *InlineObject) SetValue28endMt29(v string) {
	o.Value28endMt29 = v
}

// GetValue28endYr29 returns the Value28endYr29 field value
func (o *InlineObject) GetValue28endYr29() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Value28endYr29
}

// GetValue28endYr29Ok returns a tuple with the Value28endYr29 field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetValue28endYr29Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value28endYr29, true
}

// SetValue28endYr29 sets field value
func (o *InlineObject) SetValue28endYr29(v string) {
	o.Value28endYr29 = v
}

func (o InlineObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["r1"] = o.R1
	}
	if true {
		toSerialize["value%28D1%29"] = o.Value28D129
	}
	if true {
		toSerialize["value%28startDt%29"] = o.Value28startDt29
	}
	if true {
		toSerialize["value%28startMt%29"] = o.Value28startMt29
	}
	if true {
		toSerialize["value%28startYr%29"] = o.Value28startYr29
	}
	if true {
		toSerialize["value%28endDt%29"] = o.Value28endDt29
	}
	if true {
		toSerialize["value%28endMt%29"] = o.Value28endMt29
	}
	if true {
		toSerialize["value%28endYr%29"] = o.Value28endYr29
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject struct {
	value *InlineObject
	isSet bool
}

func (v NullableInlineObject) Get() *InlineObject {
	return v.value
}

func (v *NullableInlineObject) Set(val *InlineObject) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject(val *InlineObject) *NullableInlineObject {
	return &NullableInlineObject{value: val, isSet: true}
}

func (v NullableInlineObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


